# arguments for dataset
dataset: flare22
nclass: 14 
crop_size: [64, 128, 128]


# arguments for training
epochs: 3000
batch_size: 2   # per GPU x 4 GPUs, must be even because of the cutmix!   and the used is args.batchsize
lr: 0.1
lr_multi: 40.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95


# arguments for model
model: unet_3d
backbone: cnn
baseline: unimatch_v2_cps
lock_backbone: False